steps:
  - name: node:10.15.1
    entrypoint: npm
    args: ["install"]
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "build"]
    env:
      - 'REACT_APP_GOOGLE_CLIENT_ID=${_REACT_APP_GOOGLE_CLIENT_ID}'
      - 'PUBLIC_URL=${_PUBLIC_URL}'
  - name: node:10.15.1
    entrypoint: npm
    args: ["run", "create-env"]
    env:
      - 'MORGAN_FORMAT=${_MORGAN_FORMAT}'
      - 'SEQUELIZE_CONN_LIMIT=${_SEQUELIZE_CONN_LIMIT}'
      - 'SEQUELIZE_DIALECT=${_SEQUELIZE_DIALECT}'
      - 'SEQUELIZE_STORAGE=${_SEQUELIZE_STORAGE}'
      - 'SEQUELIZE_SSL=${_SEQUELIZE_SSL}'
      - 'SEQUELIZE_PORT=${_SEQUELIZE_PORT}'
      - 'SEQUELIZE_DB=${_SEQUELIZE_DB}'
      - 'SEQUELIZE_HOST=${_SEQUELIZE_HOST}'
      - 'SEQUELIZE_LOGGING=${_SEQUELIZE_LOGGING}'
      - 'SEQUELIZE_PASS=${_SEQUELIZE_PASS}'
      - 'SEQUELIZE_USER=${_SEQUELIZE_USER}'
      - 'SESSION_SECRET=${_SESSION_SECRET}'
      - 'REACT_APP_GOOGLE_CLIENT_ID=${_REACT_APP_GOOGLE_CLIENT_ID}'
      - 'S3_URI=${_S3_URI}'
      - 'PUBLIC_URL=${_PUBLIC_URL}'
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
timeout: "1600s"
