version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build-and-test:
        environment:
            - SEQUELIZE_URL: mysql://b4996e59ca753c:3910b720@us-cdbr-iron-east-01.cleardb.net/heroku_7606a1ead42a13b
        executor:
            name: node/default
        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: npm run build
                      - run: npm test
workflows:
    build-and-test:
        jobs:
            - build-and-test
