version: 2.1
orbs:
    node: circleci/node@1.1.6
commands:
    check-port-listening:
        parameters:
            port:
                type: string
                default: "3306"
        steps:
            - run:
                  # Our primary container isn't MYSQL so run a sleep command until it's ready.
                  name: Waiting for MySQL to be ready
                  command: |
                      for i in `seq 1 10`;
                      do
                        node is-port-listening --port=3306 && echo Success && exit 0
                        echo -n .
                        sleep 2
                      done
                      echo Failed waiting for MySQL && exit 1
jobs:
    build:
        environment:
            SEQUELIZE_URL: mysql://root:password@localhost:3306/ci
        executor:
            name: node/default
        docker:
            - image: node:12
            - image: circleci/mysql:8.0.4
              environment:
                  MYSQL_ROOT_PASSWORD: password
                  MYSQL_DATABASE: ci

        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - check-port-listening:
                           port: "3306"
                      - run: npm run build
workflows:
    build-and-test:
        jobs:
            - build
