version: 2.1
orbs:
    node: circleci/node@1.1.6
jobs:
    build:
        executor:
            name: node/default
        docker:
            - image: circleci/mysql:8.0.4
              environment:
                  MYSQL_ROOT_PASSWORD: rootpw
                  MYSQL_DATABASE: test_db
                  MYSQL_USER: user
                  MYSQL_PASSWORD: passw0rd

        steps:
            - checkout
            - node/with-cache:
                  steps:
                      - run: npm install
                      - run: node check-database-ready
workflows:
    build-and-test:
        jobs:
            - build
